// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Universities.models;

#nullable disable

namespace Universities.Migrations
{
    [DbContext(typeof(universityDBContext))]
    [Migration("20250203140651_vaddtableCommonZakat_MinorLookUpTable")]
    partial class vaddtableCommonZakat_MinorLookUpTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Universities.Entities.CommonZakat_MinorLookUpTable", b =>
                {
                    b.Property<int>("minorid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("minorid"));

                    b.Property<string>("descs")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("majorid")
                        .HasColumnType("int");

                    b.HasKey("minorid");

                    b.ToTable("CommonZakat_MinorLookUpTable", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
